version: '3.8'

services:
  mysql:
    image: mysql:latest
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: docker@12345
    networks:
      - mynetwork

  tomcat:
    image: tomcat:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: java-container
    restart: always
    ports:
      - "9090:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/testdb
      SPRING_DATASOURCE_USERNAME: testuser
      SPRING_DATASOURCE_PASSWORD: docker@12345
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
